all:

include ../kaldi.mk

TESTFILES = 

OBJFILES = lda-estimate-ext.o

LIBNAME = chenzp-transform

ADDLIBS = ../gmm/kaldi-gmm.a ../thread/kaldi-thread.a ../tree/kaldi-tree.a \
   ../util/kaldi-util.a ../matrix/kaldi-matrix.a ../base/kaldi-base.a

include ../makefiles/default_rules.mk
