

all:
EXTRA_CXXFLAGS = -Wno-sign-compare

include ../kaldi.mk

BINFILES = generate-w2s-lexicon

TESTFILES = 

OBJFILES = 

ADDLIBS = ../util/kaldi-util.a ../base/kaldi-base.a

include ../makefiles/default_rules.mk
